[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
[build]
  command = "npm run build"
  functions = "my_functions_dir"
  publish   = "my_publish_dir"

[[plugins]]
  package = "@netlify/plugin-nextjs"