[[redirects]]
  from = "/_next/image*"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/functions/image?url=:url&w=:width&q=:quality"
  status = 200
  
[build]
  command = "yarn run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"